#Jekyll
name: Spider Meadows 2022
Description: Planning Buchner-Lovell-Henjum trip 2022. 
url: https://jonathanbuchner.github.io/spider-meadows-2020/
markdown: Kramdown
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme